image_root: /data/ephemeral/home/data/test/DCM

root_path: /data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/base

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 4

threshold: 0.5

model_paths:
  512: []
  1024: []
  1536: []
  2048: 
    - '/data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/Ultralytics/last-yolo/fold1/weights/best.pt'
    - '/data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/Ultralytics/last-yolo/fold2/weights/best.pt'
    - '/data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/Ultralytics/last-yolo/fold3/weights/best.pt'
    - '/data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/Ultralytics/last-yolo/fold4/weights/best.pt'
    - '/data/ephemeral/home/kgs/level2-cv-semanticsegmentation-cv-8-lv3/Ultralytics/last-yolo/fold5/weights/best.pt'

save_dir: ./soft_ensemble
output_name: yolo_soft_ensemble.csv